server:
  port: 8888
spring:
  application:
    name: ahm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/augustomentz/ahm-microservices
          default-label: main
          search-paths:
            - 'ahm-configurations/greeting-app*'