spring:
  application:
    name: greeting-app
  config:
    import:
    - "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-app:
  greeting: "Hello"
  default-value: "World of PROD!"